### ISSUE TITLE
Changing Open Menu Key

### ISSUE THREAD

**Issue by TheDevster** [RodericAguilar/Roda_Animations#2]
For whatever reason I am having troubles changing the menu open key from F3 to F2, no matter what I change it to, it still only activates on F3.

**Comment by Taavi-AU** [comment]
Thats because it uses key mapping and the key map has registered, so this means new players will have F2 but since it has already registered for you, you have to go into FiveM Keybinds and change it

**Comment by TheDevster** [comment]
Thanks @Taavi-AU , this was the issue.
